services:
  # PHP Service
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - ./storage:/var/www/html/storage
    networks:
      - app-network
    depends_on:
      - mysql
    user: "${UID:-1000}:${GID:-1000}"

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: MyTestApp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node Service for React development
  node:
    image: node:18-alpine
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  queue-worker:
    build: .
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - app
      - mysql
    user: "${UID:-1000}:${GID:-1000}"
    command: php artisan queue:work --verbose --tries=3 --timeout=90

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  node_modules:
